spring:
  application:
  name: langchain4j-consutant
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/volunteer?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: hsp
  data:
    redis:
      host: localhost
      port: 6379
      database: 0


mybatis:
  configuration:
    map-underscore-to-camel-case: true
langchain4j:
  open-ai:
    chat-model:
      model-name: qwq-plus
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      log-requests: true
      log-responses: false
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen-plus
      log-requests: true
      log-responses: true
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: text-embedding-v3
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10
  community:
    redis:
      host: localhost
      port: 6380
      password: 123456
      user: default
logging:
  level:
    dev.langchain4j: debug
